# Generated by Django 4.0.4 on 2022-08-12 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mob', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.CharField(max_length=255)),
                ('complaint_status', models.PositiveIntegerField(choices=[(1, 'Registred'), (2, 'In Progress'), (3, 'Repaired'), (4, 'Failed'), (5, 'Repaired and Closed'), (6, 'Failed and Closed')], default=0)),
                ('registred_date', models.DateField(default=datetime.datetime.now)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=256)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('model_no', models.CharField(max_length=256)),
                ('serial_no', models.CharField(blank=True, max_length=256, null=True)),
                ('pre_repair_checklist', models.JSONField(max_length=5000)),
                ('physical_condition', models.CharField(max_length=2048)),
                ('problem', models.CharField(max_length=5000)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('closed_by', models.ForeignKey(blank=True, db_column='closed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_by', to=settings.AUTH_USER_MODEL, verbose_name='Closed_By')),
                ('registred_by', models.ForeignKey(blank=True, db_column='registred_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registred_by', to=settings.AUTH_USER_MODEL, verbose_name='Registred By')),
                ('resolved_by', models.ForeignKey(blank=True, db_column='resolved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to=settings.AUTH_USER_MODEL, verbose_name='Resolved_By')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=125)),
                ('item_description', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
            ],
        ),
    ]
