# Generated by Django 4.0.4 on 2022-07-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mob', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.CharField(max_length=255)),
                ('complaint_status', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_model', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=255)),
                ('registred_date', models.DateField(auto_now=True)),
                ('resolved_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=125)),
                ('item_description', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='components_used',
            field=models.ManyToManyField(related_name='components_used', to='complaint.item'),
        ),
    ]
