# Generated by Django 4.0.4 on 2022-08-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='model_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='physical_condition',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='pre_repair_checklist',
            field=models.JSONField(blank=True, max_length=5000, null=True),
        ),
    ]
