# Generated by Django 4.1.3 on 2023-01-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='warrenty',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
