# Generated by Django 4.1.3 on 2023-02-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_item_category_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified_on_close', default=False),
        ),
    ]
