# Generated by Django 4.0.4 on 2022-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='components_used',
            field=models.ManyToManyField(related_name='components_used', to='complaint.item', verbose_name='Components Used'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateField(auto_now=True),
        ),
    ]
