# Generated by Django 4.1.3 on 2023-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complaint_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='serial_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
