# Generated by Django 4.0.4 on 2022-07-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0003_alter_complaint_components_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='registred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registred_by', to=settings.AUTH_USER_MODEL, verbose_name='Registred By'),
        ),
    ]
