# Generated by Django 4.1.3 on 2023-02-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaint_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
            ],
        ),
    ]
