# Generated by Django 4.1.3 on 2023-02-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_complaintotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintotp',
            name='otp',
            field=models.CharField(max_length=10),
        ),
    ]
