# Generated by Django 4.0.4 on 2022-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_alter_complaint_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='components_used',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
