# Generated by Django 4.0.4 on 2022-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_remove_complaint_components_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
