# Generated by Django 4.0.4 on 2022-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_complaint_assigned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='product_name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='complaint',
            name='product_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
