# Generated by Django 4.0.4 on 2022-07-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_rename_product_name_complaint_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='product',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.PositiveIntegerField(choices=[(0, 'Registred'), (1, 'In Progress'), (2, 'Repaired'), (3, 'Failed'), (4, 'Repaired ans Closed'), (5, 'Failed and Closed')], default=0),
        ),
    ]
