# Generated by Django 4.0.4 on 2022-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_rename_product_complaint_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.PositiveIntegerField(choices=[(1, 'Registred'), (2, 'In Progress'), (3, 'Repaired'), (4, 'Failed'), (5, 'Repaired and Closed'), (6, 'Failed and Closed')], default=0),
        ),
    ]
