# Generated by Django 4.0.5 on 2022-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_alter_complaint_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='problem',
            field=models.CharField(max_length=3000),
        ),
    ]
