# Generated by Django 4.0.4 on 2022-07-28 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_alter_complaint_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='registred_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
