# Generated by Django 4.0.4 on 2022-08-07 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0014_alter_complaint_registred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='registred_by',
            field=models.ForeignKey(blank=True, db_column='registred_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registred_by', to=settings.AUTH_USER_MODEL, verbose_name='Registred By'),
        ),
    ]
