# Generated by Django 4.1.2 on 2022-10-28 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('desc', models.CharField(blank=True, max_length=3000)),
                ('quantity', models.IntegerField()),
                ('warrenty', models.PositiveIntegerField()),
                ('unit_price', models.IntegerField()),
                ('registred_on', models.DateField(blank=True, null=True)),
                ('registred_by', models.ForeignKey(blank=True, db_column='p_registred_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_registred_by', to=settings.AUTH_USER_MODEL, verbose_name='Registred By')),
            ],
        ),
    ]
