# Generated by Django 4.0.4 on 2022-07-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='joinDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='username',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
