# Generated by Django 4.0.4 on 2022-07-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_employee_is_employee_employee_is_engineer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
