# Generated by Django 4.0.4 on 2022-07-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_employee_user_alter_engineer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='name',
        ),
    ]
