# Generated by Django 4.0.4 on 2022-07-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_alter_complaint_assigned_to_and_more'),
        ('user', '0008_employee_registred_complaints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='assigend_complaints',
            field=models.ManyToManyField(blank=True, default=None, related_name='assigned_complaints', to='complaint.complaint'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='complaints_resolved',
            field=models.ManyToManyField(blank=True, default=None, related_name='complaints_resolved', to='complaint.complaint'),
        ),
    ]
