# Generated by Django 4.0.4 on 2022-07-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_alter_complaint_assigned_to_and_more'),
        ('user', '0009_alter_engineer_assigend_complaints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='assigend_complaints',
        ),
        migrations.AddField(
            model_name='engineer',
            name='assigend_complaints',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='complaint.complaint', verbose_name='Assigned Complaints'),
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='complaints_resolved',
        ),
        migrations.AddField(
            model_name='engineer',
            name='complaints_resolved',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_resolved', to='complaint.complaint', verbose_name='Complaints Resolved'),
        ),
    ]
