# Generated by Django 4.0.4 on 2022-07-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_engineer_assigend_complaints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='registred_complaints',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='assigend_complaints',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='complaints_resolved',
        ),
    ]
