# Generated by Django 4.0.4 on 2022-07-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_employee_registred_complaints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_engineer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_profile_completed',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='is_engineer',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='is_profile_completed',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mob',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='mob',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
